# Generated by Django 5.1.15 on 2026-09-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=128)),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('decommissioned', 'Decommissioned'), ('planned', 'Planned')], max_length=32)),
                ('ip_address', models.GenericIPAddressField()),
                ('fqdn', models.CharField(max_length=255)),
                ('os_platform', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('prod', 'Prod'), ('stage', 'Stage'), ('dev', 'Dev'), ('test', 'Test')], max_length=16)),
                ('criticality', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('inventory_number', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=255)),
                ('commissioned_at', models.DateField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenants.contour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('security_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secured_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype')),
                ('business_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.businesssystem')),
            ],
            options={
                'ordering': ['business_system__name', 'name'],
                'indexes': [models.Index(fields=['tenant', 'environment'], name='assets_asse_tenant__919c2d_idx'), models.Index(fields=['tenant', 'status'], name='assets_asse_tenant__155bcb_idx')],
            },
        ),
    ]
