# Generated by Django 5.1.15 on 2026-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kill_sync_nvd', models.BooleanField(default=False)),
                ('kill_sync_kev', models.BooleanField(default=False)),
                ('kill_sync_bdu', models.BooleanField(default=False)),
                ('kill_outbound_mail', models.BooleanField(default=False)),
                ('kill_sso', models.BooleanField(default=False)),
                ('kill_product_updates', models.BooleanField(default=False)),
                ('kill_2fa_totp', models.BooleanField(default=False)),
                ('global_nvd_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('setup_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
