# Generated by Django 5.1.15 on 2026-09-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('nvd', 'NVD'), ('kev', 'CISA KEV'), ('bdu', 'BDU FSTEC')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='manual', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('nvd', 'NVD'), ('kev', 'CISA KEV'), ('bdu', 'BDU FSTEC')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_hours', models.PositiveIntegerField(blank=True, default=24, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('run_dates', models.JSONField(blank=True, default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('bdu_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_kev', models.BooleanField(db_index=True, default=False)),
                ('kev_date_added', models.DateField(blank=True, null=True)),
                ('kev_due_date', models.DateField(blank=True, null=True)),
                ('kev_ransomware', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('cvss_v2_score', models.FloatField(blank=True, null=True)),
                ('cvss_v2_vector', models.CharField(blank=True, default='', max_length=128)),
                ('cvss_v3_score', models.FloatField(blank=True, null=True)),
                ('cvss_v3_vector', models.CharField(blank=True, default='', max_length=128)),
                ('cvss_v31_score', models.FloatField(blank=True, null=True)),
                ('cvss_v31_vector', models.CharField(blank=True, default='', max_length=128)),
                ('cvss_v4_score', models.FloatField(blank=True, null=True)),
                ('cvss_v4_vector', models.CharField(blank=True, default='', max_length=128)),
                ('max_cvss', models.FloatField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('cwe_ids', models.JSONField(blank=True, default=list)),
                ('cpe_list', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('nvd_raw', models.JSONField(blank=True, default=dict)),
                ('bdu_raw', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='active', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-max_cvss', '-published_at'],
                'indexes': [models.Index(fields=['tenant', 'max_cvss'], name='vulnerabili_tenant__efa855_idx'), models.Index(fields=['tenant', 'is_kev'], name='vulnerabili_tenant__9efd31_idx'), models.Index(fields=['tenant', 'cve_id'], name='vulnerabili_tenant__f1fe86_idx'), models.Index(fields=['tenant', 'bdu_id'], name='vulnerabili_tenant__1b0433_idx')],
            },
        ),
    ]
