# Generated by Django 5.1.15 on 2026-09-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('primary_color', models.CharField(default='#1E4FD6', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('accent_color', models.CharField(default='#0B2A6F', max_length=7)),
                ('feature_sync_nvd', models.BooleanField(default=True)),
                ('feature_sync_kev', models.BooleanField(default=True)),
                ('feature_sync_bdu', models.BooleanField(default=True)),
                ('feature_outbound_mail', models.BooleanField(default=False)),
                ('feature_sso', models.BooleanField(default=False)),
                ('feature_product_updates', models.BooleanField(default=True)),
                ('feature_2fa_totp', models.BooleanField(default=False)),
                ('offline_mode', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from', models.EmailField(blank=True, default='', max_length=254)),
                ('nvd_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('session_idle_minutes', models.PositiveIntegerField(default=60)),
                ('audit_retention_days', models.PositiveIntegerField(default=180)),
                ('sso_provider', models.CharField(blank=True, choices=[('', 'None'), ('oidc', 'OIDC'), ('saml', 'SAML'), ('ldap', 'LDAP'), ('ad', 'Active Directory')], default='', max_length=32)),
                ('sso_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workday_start', models.TimeField(default='09:00')),
                ('workday_end', models.TimeField(default='18:00')),
                ('workdays', models.JSONField(default=list)),
                ('exceptions', models.JSONField(default=list)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Security Analyst'), ('asset_owner', 'Asset Owner'), ('reader', 'Reader'), ('wiki_editor', 'Wiki Editor')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField()),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
